version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: sounds
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: haslo1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sounds
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: haslo1234
  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
volumes:
  postgres_data:
